branches:
  only:
    - master

# NOTE: only static linking, i.e. via .lib file supported
#  -D BUILD_SHARED_LIBS=OFF;
# extern "C" {  would have to be added to subprojects

build_script:
  - git submodule update --init --recursive
  - cmake -E make_directory build
  - cmake -E chdir build cmake -D BLASFEO_TARGET=GENERIC -D HPIPM_TARGET=GENERIC -D BUILD_SHARED_LIBS=OFF -D ACADOS_EXAMPLES=ON ..
  - cmake --build build --config Release
  - cmake -E chdir build ctest -V
  