dist: trusty
sudo: required
language: python
python:
  - 3.5

env:
  - CXX="g++-6" CC="gcc-6"
  - CXX="g++-5" CC="gcc-5"
  - CXX="g++-4.9" CC="gcc-4.9"
  - CXX="clang++-3.7" CC="clang-3.7"

addons:
  apt:
    sources:
    - llvm-toolchain-precise-3.7
    - ubuntu-toolchain-r-test

before_install:
  - echo "TRAVIS_REPO_SLUG=$TRAVIS_REPO_SLUG TRAVIS_PULL_REQUEST=$TRAVIS_PULL_REQUEST TRAVIS_BRANCH=$TRAVIS_BRANCH"
  - 'if [ "$TRAVIS_REPO_SLUG" == "acados/acados" -a "$TRAVIS_PULL_REQUEST" == "false" ]; then
      openssl aes-256-cbc -K $encrypted_15c483c21b41_key -iv $encrypted_15c483c21b41_iv -in external/encrypted_scripts.tar.enc -out external/encrypted_scripts.tar -d;
      tar -xvf external/encrypted_scripts.tar -C external;
    fi'
  # get rid of old gcc installation
  - echo 'Yes, do as I say!' | sudo apt-get remove --force-yes libstdc++-4.8-dev libgfortran-4.8-dev libgcc-4.8-dev gcc-4.8-base gcc-4.8 g++-4.8 cpp-4.8
  
install:
  - pushd external
  - 'if [ "$TRAVIS_REPO_SLUG" == "acados/acados" -a "$TRAVIS_PULL_REQUEST" == "false" ]; then
      source download_encrypted_files.sh;
    fi'
  - popd
  - travis_retry source install_packages.sh
  - export MPLBACKEND=Agg # For matplotlib
  - export MATLABPATH=$HOME/local/lib:$MATLABPATH
  - export PYTHONPATH=$HOME/local/lib:$PYTHONPATH

before_script:
  - set -e

script:
  - cmake -E make_directory build
  - cmake -E chdir build cmake -D CMAKE_BUILD_TYPE=Test ..
  - cmake --build build --clean-first
  - cmake --build build --target install
  - cmake --build build --target lint
  - ldd $HOME/local/lib/acadosMEX.mexa64
  - nm -D $HOME/local/lib/acadosMEX.mexa64
  - nm -D /usr/lib/x86_64-linux-gnu/libstdc++.so.6
  - echo $LD_LIBRARY_PATH
  - export LD_LIBRARY_PATH=/usr/lib/x86_64-linux-gnu:$LD_LIBRARY_PATH
  - find /usr | grep libstdc++
  - find /usr -type l -ls | grep libstdc++
  - cmake -E chdir build ctest --output-on-failure
  - cmake -E chdir build cmake -D CMAKE_BUILD_TYPE=Release ..
  - cmake --build build --clean-first
  - cmake -E chdir build cmake -D CMAKE_BUILD_TYPE=Debug ..
  - cmake --build build --clean-first
  - pushd experimental/dang/esp32
  - ./test_all_linux.sh
