# explicitly request container-based infrastructure
sudo: true
 
env:
 - CXX="g++-6" CC="gcc-6"
 - CXX="clang++-3.7" CC="clang-3.7"

addons:
  apt:
    sources:
      - llvm-toolchain-precise-3.7
      - ubuntu-toolchain-r-test
    packages:
      - libgsl0-dev
      - liblapack-dev
      - cppcheck
      - cmake
      - clang-3.7
      - gcc-6
      - g++-6

before_install:
 - sudo add-apt-repository -y ppa:octave/stable
 - sudo apt-get update -qq
 - sudo apt-get install octave octave-struct octave-optim

install:
 - pushd external
 - wget http://bitbucket.org/eigen/eigen/get/3.2.10.tar.gz
 - mkdir eigen
 - tar -xf 3.2.10.tar.gz --strip-components=1 -C eigen
 - popd

script:
 - set -e
 - git submodule init
 - git submodule update
 - mkdir build
 - cd build
 - cmake -D CMAKE_BUILD_TYPE=Test ..
 - set +e
 - make lint
 - make unit_tests
 - cd test
 - ./unit_tests
