# explicitly request container-based infrastructure
sudo: false

compiler:
 - clang-3.7

env:
 # currently unused
 - CC=clang-3.7

addons:
  apt:
#    sources:
    packages:
    - libgsl0-dev
    - liblapack-dev
    - cppcheck
    - cmake
    - clang-3.7

script:
 - git submodule init
 - git submodule update
 - mkdir build
 - cd build
 - cmake ..
 - make test_acados
 - ./test_acados
 - make lint
