matrix:
  include:
    - os: osx
      osx_image: xcode9.4
      language: c
      env:
        - SCRIPT_DIR="${TRAVIS_BUILD_DIR}/ci/${TRAVIS_OS_NAME}"
        - SHARED_SCRIPT_DIR="${TRAVIS_BUILD_DIR}/ci/shared"

        - CASADI_INSTALL_DIR="${HOME}/casadi"
        - ACADOS_INSTALL_DIR="${HOME}/acados"

cache:
  ccache: true
  directories:
      - "${CASADI_INSTALL_DIR}"

install:
  - travis_retry source "${SCRIPT_DIR}/install.sh"

script:
  - travis_retry source "${SCRIPT_DIR}/script.sh"