# explicitly request container-based infrastructure
dist: precise
sudo: true

env:
 - CXX="g++-6" CC="gcc-6" FC="gfortran-6"
 - CXX="g++-5" CC="gcc-5" FC="gfortran-5"
 - CXX="g++-4.9" CC="gcc-4.9" FC="gfortran-4.9"
 - CXX="clang++-3.7" CC="clang-3.7"

addons:
  apt:
    sources:
      - llvm-toolchain-precise-3.7
      - ubuntu-toolchain-r-test
    packages:
      - libgsl0-dev
      - liblapack-dev
      - cppcheck
      - g++-6
      - gcc-6
      - g++-4.9
      - gcc-4.9
      - g++-5
      - gcc-5
      - clang-3.7

before_install:
 - openssl aes-256-cbc -K $encrypted_5f97e87a5b89_key -iv $encrypted_5f97e87a5b89_iv -in external/encrypted_script.enc -out external/encrypted_script -d
 - sudo add-apt-repository -y ppa:octave/stable
 - sudo add-apt-repository -y ppa:george-edison55/precise-backports
 - sudo apt-get update -qq
 - sudo apt-get install r-base-dev # TODO(dimitris): maybe not needed?
 - sudo apt-get install octave liboctave-dev cmake-data cmake

install:
 - pushd external
 - source encrypted_script
 - wget http://bitbucket.org/eigen/eigen/get/3.2.10.tar.gz
 - mkdir eigen
 - tar -xvf 3.2.10.tar.gz --strip-components=1 -C eigen
 - wget http://files.casadi.org/3.1.1/linux/casadi-octave-v3.1.1.tar.gz
 - mkdir casadi-octave-v3.1.1
 - tar -xvf casadi-octave-v3.1.1.tar.gz -C casadi-octave-v3.1.1
 - popd

script:
 - set -e
 - git submodule init
 - git submodule update
 - mkdir build
 - cd build
 - cmake -D CMAKE_BUILD_TYPE=Test ..
 - set +e
 - make lint
 - make unit_tests
 - cd test
 - ./unit_tests
