language: c
env:
  global:
    - CASADIPATH="${HOME}/casadi"
    - ACADOS_INSTALL_DIR="${HOME}/acados"
    - DEPLOY_FOLDER="${HOME}/deploy"

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    - deadsnakes

matrix:
  include:
    - name: MacOS Python Interface Build
      os: osx
      osx_image: xcode9.4
      env:
        - DEPLOY_NAME="osx-python"
    - name: Linux Python Interface Build
      os: linux
      sudo: required
      dist: trusty
      env:
        - DEPLOY_NAME="linux-python"
        - CXX="g++-6"
        - CC="gcc-6"

cache:
  ccache: true
  directories:
      - "${CASADIPATH}"

before_install:
  - export SCRIPT_DIR="${TRAVIS_BUILD_DIR}/ci/${TRAVIS_OS_NAME}"
  - export SHARED_SCRIPT_DIR="${TRAVIS_BUILD_DIR}/ci/shared"

install:
  - source "${SCRIPT_DIR}/install.sh"

script:
  - source "${SCRIPT_DIR}/script.sh"

after_success:
  - mkdir -p "${DEPLOY_FOLDER}"
  - source "${SCRIPT_DIR}/after_success.sh"

deploy:
  provider: releases
  api_key: "${GITHUB_OAUTH_TOKEN}"
  file_glob: true
  file: "${DEPLOY_FOLDER}/*"
  skip_cleanup: true