dist: trusty
sudo: required
language: python
python:
  - 3.5

env:
  - CXX="g++-6" CC="gcc-6"
  - CXX="g++-5" CC="gcc-5"
  - CXX="g++-4.9" CC="gcc-4.9"
  - CXX="clang++-3.7" CC="clang-3.7"

addons:
  apt:
    sources:
    - llvm-toolchain-precise-3.7
    - ubuntu-toolchain-r-test
    packages:
      - libgsl0-dev
      - liblapack-dev
      - libopenblas-dev
      - cppcheck
      - g++-6
      - gcc-6
      - g++-4.9
      - gcc-4.9
      - gfortran-4.9
      - g++-5
      - gcc-5
      - clang-3.7
      - swig

before_install:
  - echo "TRAVIS_REPO_SLUG=$TRAVIS_REPO_SLUG TRAVIS_PULL_REQUEST=$TRAVIS_PULL_REQUEST TRAVIS_BRANCH=$TRAVIS_BRANCH"
  - 'if [ "$TRAVIS_REPO_SLUG" == "acados/acados" -a "$TRAVIS_PULL_REQUEST" == "false" ]; then
      openssl aes-256-cbc -K $encrypted_15c483c21b41_key -iv $encrypted_15c483c21b41_iv
      -in external/download_software.enc -out external/download_software -d;
      openssl aes-256-cbc -K $encrypted_15c483c21b41_key -iv $encrypted_15c483c21b41_iv
      -in external/download_matlab.enc -out external/download_matlab -d;
    fi'

install:
  - pushd external
  - 'if [ "$TRAVIS_REPO_SLUG" == "acados/acados" -a "$TRAVIS_PULL_REQUEST" == "false" ]; then
      source download_encrypted_files.sh;
    fi'
  - popd
  - travis_retry source install_packages.sh
  - export MPLBACKEND=Agg # For matplotlib
  - export PYTHONPATH=$HOME/local/lib:$PYTHONPATH # For acados

script:
  - cmake -E make_directory build
  - cmake -E chdir build cmake -D CMAKE_BUILD_TYPE=Test ..
  - cmake --build build --clean-first
  - cmake --build build --target install
  - cmake --build build --target lint
  - cmake -E chdir build ctest --output-on-failure
  - cmake -E chdir build cmake -D CMAKE_BUILD_TYPE=Release ..
  - cmake --build build --clean-first
  - cmake -E chdir build cmake -D CMAKE_BUILD_TYPE=Debug ..
  - cmake --build build --clean-first
  - pushd experimental/dang/esp32
  - ./test_all_linux.sh
