# explicitly request container-based infrastructure
sudo: false

compiler:
 - gcc
 - clang

install:
- if [ "$CXX" = "g++" ]; then export CXX="g++-6" CC="gcc-6"; fi
- if [ "$CXX" = "clang++" ]; then export CXX="clang++-3.7" CC="clang-3.7"; fi

addons:
  apt:
    sources:
      - llvm-toolchain-precise-3.7
      - ubuntu-toolchain-r-test
    packages:
      - libgsl0-dev
      - liblapack-dev
      - cppcheck
      - cmake
      - clang-3.7
      - gcc-6
      - g++-6

script:
 - set -e
 - CC --version
 - CXX --version
 - git submodule init
 - git submodule update
 - mkdir build
 - cd build
 - cmake ..
 - set +e
 - make lint
 - make test_condensing_qpoases
 - ./test_condensing_qpoases
 - make test_nmpc
 - ./test_nmpc
 - make test_chain
 - ./test_chain
