language: c
env:
  global:
    - CASADIPATH="${HOME}/casadi"
    - ACADOS_INSTALL_DIR="${HOME}/acados"
    - DEPLOY_FOLDER="${HOME}/deploy"

os: linux
sudo: required
dist: trusty

addons:
  apt:
    sources:
      - llvm-toolchain-precise-3.7
      - ubuntu-toolchain-r-test
      - deadsnakes

matrix:
  include:
    - name: MacOS Python Interface Build
      os: osx
      osx_image: xcode9.4
      env:
        - DEPLOY_NAME="osx-python"
    - name: Linux Python Interface Gcc6
      env:
        - DEPLOY_NAME="linux-python"
        - MATRIX_EVAL="CC=gcc-6 && CXX=g++-6"
    - name: Linux Python Interface Gcc5
      env:
        - DEPLOY_NAME="linux-python"
        - MATRIX_EVAL="CC=gcc-5 && CXX=g++-5"
    - name: Linux Python Interface Gcc4.9
      env:
        - DEPLOY_NAME="linux-python"
        - MATRIX_EVAL="CC=gcc-4.9 && CXX=g++-4.9"
    - name: Linux Python Interface Clang
      env:
        - DEPLOY_NAME="linux-python"
        - MATRIX_EVAL="CC=clang-3.7 && CXX=clang++-3.7"

cache:
  ccache: true
  directories:
      - "${CASADIPATH}"

before_install:
  - eval "${MATRIX_EVAL}"
  - SECTION='before_install'
  - export SCRIPT_DIR="${TRAVIS_BUILD_DIR}/ci/${TRAVIS_OS_NAME}"
  - export SHARED_SCRIPT_DIR="${TRAVIS_BUILD_DIR}/ci/shared"
  - source "${SCRIPT_DIR}/dispatch.sh"

install:
  - SECTION='install'
  - source "${SCRIPT_DIR}/dispatch.sh"

script:
  - SECTION='script'
  - source "${SCRIPT_DIR}/dispatch.sh"

after_success:
  - SECTION='after_success'
  - mkdir -p "${DEPLOY_FOLDER}"
  - source "${SCRIPT_DIR}/dispatch.sh"

deploy:
  provider: releases
  api_key: "${GITHUB_OAUTH_TOKEN}"
  file_glob: true
  file: "${DEPLOY_FOLDER}/*"
  skip_cleanup: true