# explicitly request container-based infrastructure
sudo: false

compiler: 
 - clang

env:
 # currently unused

addons:
  apt:
#    sources:
    packages:
    - libgsl0-dev
    - liblapack-dev
    - cppcheck
    - cmake

script:
 - git submodule init
 - git submodule update
 - mkdir build
 - cd build
 - cmake ..
 - make test_acados
 - ./test_acados
 - make lint
