# explicitly request container-based infrastructure
sudo: false
 
compiler:
 - clang
 - gcc

addons:
  apt:
    sources:
      - llvm-toolchain-precise-3.7
      - ubuntu-toolchain-r-test
    packages:
      - libgsl0-dev
      - liblapack-dev
      - cppcheck
      - cmake
      - clang-3.7
      - gcc-6
      - g++-6
      
install:
 - if [ "$CXX" = "g++" ]; then export CXX="g++-6" export CC="gcc-6"; fi
 - if [ "$CXX" = "clang++" ]; then export CXX="clang++-3.7" export CC="clang-3.7"; fi

script:
 - set -e
 - git submodule init
 - git submodule update
 - mkdir build
 - cd build
 - cmake ..
 - set +e
 - make lint
 - make test_condensing_qpoases
 - ./test_condensing_qpoases
 - make test_nmpc
 - ./test_nmpc
 - make test_chain
 - ./test_chain
