dist: trusty
sudo: required
language: python
python:
  - 3.6

env:
  - CXX="g++-6" CC="gcc-6"
  - CXX="g++-5" CC="gcc-5"
  - CXX="g++-4.9" CC="gcc-4.9"
  - CXX="g++-4.8" CC="gcc-4.8"
  - CXX="clang++-3.7" CC="clang-3.7"

addons:
  apt:
    sources:
    - llvm-toolchain-precise-3.7
    - ubuntu-toolchain-r-test
    packages:
      - libgsl0-dev
      - liblapack-dev
      - libopenblas-base
      - libopenblas-dev
      - cppcheck
      - g++-6
      - gcc-6
      - g++-4.9
      - gcc-4.9
      - gfortran-4.9
      - g++-5
      - gcc-5
      - clang-3.7
      - swig

before_install:
  - echo "TRAVIS_REPO_SLUG=$TRAVIS_REPO_SLUG TRAVIS_PULL_REQUEST=$TRAVIS_PULL_REQUEST TRAVIS_BRANCH=$TRAVIS_BRANCH"
  - 'if [ "$TRAVIS_REPO_SLUG" == "acados/acados" -a "$TRAVIS_PULL_REQUEST" == "false" ]; then
      openssl aes-256-cbc -K $encrypted_953dc9b02fae_key -iv $encrypted_953dc9b02fae_iv
      -in external/encrypted_script.enc -out external/encrypted_script -d;
    fi'
  - sudo add-apt-repository -y ppa:octave/stable
  - sudo apt-get update -yq

install:
  - pip install numpy
  - sudo apt-get install octave liboctave-dev
  - pushd external
  - 'if [ "$TRAVIS_REPO_SLUG" == "acados/acados" -a "$TRAVIS_PULL_REQUEST" == "false" ]; then
      source encrypted_script;
    fi'
  - travis_retry wget http://bitbucket.org/eigen/eigen/get/3.2.10.tar.gz
  - mkdir eigen
  - tar -xvf 3.2.10.tar.gz --strip-components=1 -C eigen
  - travis_retry wget http://files.casadi.org/3.1.1/linux/casadi-octave-v3.1.1.tar.gz
  - mkdir casadi-octave-v3.1.1
  - tar -xvf casadi-octave-v3.1.1.tar.gz -C casadi-octave-v3.1.1
  - popd

script:
  - set -e
  - git submodule init
  - git submodule update
  - mkdir build
  - cd build
  - cmake -D CMAKE_BUILD_TYPE=Test ..
  - set +e
  - make
  - make lint
  - make unit_tests
  - make install
  - pushd test
  - ./unit_tests
  - popd
  - pushd $VIRTUAL_ENV
  - python3 test_swig.py
  - popd
  - cmake -D CMAKE_BUILD_TYPE=Release ..
  - make
  - cmake -D CMAKE_BUILD_TYPE=Debug ..
  - make
