# explicitly request container-based infrastructure
sudo: false

compiler:
 - gcc
 - clang-3.7
 
env:
 - CXX=g++-4.8

install:
- if [ "$CXX" = "g++" ]; then export CXX="g++-4.8" CC="gcc-4.8"; fi

addons:
  apt:
    sources:
      - llvm-toolchain-precise-3.7
      - ubuntu-toolchain-r-test
    packages:
      - libgsl0-dev
      - liblapack-dev
      - cppcheck
      - cmake
      - clang-3.7
      - gcc-4.8
      - g++-4.8
      - clang

script:
 - set -e
 - gcc --version
 - git submodule init
 - git submodule update
 - mkdir build
 - cd build
 - cmake ..
 - set +e
 - make lint
 - make test_condensing_qpoases
 - ./test_condensing_qpoases
 - make test_nmpc
 - ./test_nmpc
 - make test_chain
 - ./test_chain
