# explicitly request container-based infrastructure
sudo: false

compiler:
 - clang-3.9

env:
 # currently unused
 - CC=clang-3.9
 - CXX=clang-3.9

addons:
  apt:
    sources:
      - llvm-toolchain-precise-3.9
      - ubuntu-toolchain-r-test
    packages:
      - libgsl0-dev
      - liblapack-dev
      - cppcheck
      - cmake
      - clang-3.9
      - gcc-6

script:
 - set -e
 - git submodule init
 - git submodule update
 - mkdir build
 - cd build
 - cmake ..
 - make lint
 - make test_condensing_qpoases
 - ./test_condensing_qpoases
 - make test_nmpc
 - ./test_nmpc
 - make test_chain
 - ./test_chain
